/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RAaHJ5stGwY
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function Component() {
  return (
    (<Card className="w-full max-w-3xl">
      <CardHeader className="flex flex-row items-center space-y-0">
        <CardTitle>Company Search</CardTitle>
        <Button className="ml-auto rounded-full" size="icon" variant="outline">
          <ChevronRightIcon className="h-4 w-4" />
          <span className="sr-only">Search</span>
        </Button>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="grid gap-0.5">
          <Label className="text-sm" htmlFor="company">
            Company
          </Label>
          <Input id="company" placeholder="Enter company name" />
        </div>
        <Button size="sm">Search</Button>
      </CardContent>
    </Card>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
